version: '3.8'

services:
#  ngrok:
#    image: ngrok/ngrok:latest
#    command: http host.docker.internal:8080
#    environment:
#      - NGROK_AUTHTOKEN=
#    ports:
#      - 4040:4040

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./.init-db:/docker-entrypoint-initdb.d

  profileService:
    build:
      context: ./profiles/
      dockerfile: ../Dockerfile
    image: profiles_service:latest
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/gymbrodb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"

  likesService:
    build:
      context: ./likes/
      dockerfile: ../Dockerfile
    image: likes_service:latest
    depends_on:
      - postgres
      # - kafka
    environment:
      SPRING_LIKES_DATASOURCE_URL: jdbc:postgresql://postgres:5432/likesdb
      SPRING_LIKES_DATASOURCE_USERNAME: postgres
      SPRING_LIKES_DATASOURCE_PASSWORD: postgres
      NOTIFICATION_SERVICE_URL: "http://localhost:8082"
    ports:
      - "8081:8080"

  notificationsService:
    build:
      context: ./notifications/
      dockerfile: ../Dockerfile
    image: notifications_service:latest
#    depends_on:
#       - kafka
    ports:
      - "8082:8080"

  deckShufflingService:
    build:
      context: ./deckShuffle/
      dockerfile: ../Dockerfile
    image: deck_shuffle_service:latest
    depends_on:
      - postgres
    ports:
      - "8083:8080"


volumes:
  postgres_data:
