version: '3.8'

services:
  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./.init-db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${PROFILE_DB_USER}
      POSTGRES_PASSWORD: ${PROFILE_DB_USER}

  profileService:
    build:
      context: ./profiles/
      dockerfile: ../Dockerfile
    image: profiles_service:latest
    environment:
      SPRING_DATASOURCE_URL: ${PROFILE_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${PROFILE_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${PROFILE_DB_PASSWORD}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    ports:
       - "8080:8080"
    depends_on:
      - db

  likesService:
    build:
      context: ./likes/
      dockerfile: ../Dockerfile
    image: likes_service:latest
    depends_on:
      - notificationsService
      - db
    environment:
      SPRING_LIKES_DATASOURCE_URL: ${LIKES_DB_URL}
      SPRING_LIKES_DATASOURCE_USERNAME: ${LIKES_DB_USERNAME}
      SPRING_LIKES_DATASOURCE_PASSWORD: ${LIKES_DB_PASSWORD}
      NOTIFICATION_SERVICE_URL: "http://notifications:8080"
    ports:
      - "8081:8080"

  notificationsService:
    build:
      context: ./notifications/
      dockerfile: ../Dockerfile
    container_name: notifications
    image: notifications_service:latest
    ports:
      - "8082:8080"
    depends_on:
      - db

  deckShufflingService:
    build:
      context: ./deckShuffle/
      dockerfile: ../Dockerfile
    container_name: deck_shuffle
    image: deck_shuffle_service:latest
    depends_on:
      - profileService
      - db
    environment:
      SPRING_DATASOURCE_URL: ${PROFILE_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${PROFILE_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${PROFILE_DB_PASSWORD}
    ports:
      - "8083:8080"


volumes:
  postgres_data:
