version: '3.8'

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: gymbroDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: solarwind
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5440/gymbroDB
    ports:
      - "8080:8080"

volumes:
  postgres_data: