name: Deploy to remote server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy on remote server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_HOST_USER }}
          key: ${{ secrets.REMOTE_HOST_SSH_KEY }}
          script: |
            APP_DIR=~/app

            if [ -d "$APP_DIR" ]; then
              cd $APP_DIR
              git fetch origin
              git reset --hard origin/main
            else
              git clone https://github.com/${{ github.repository }} $APP_DIR
              cd $APP_DIR
            fi
            cd backend

            cat > .env <<EOF
            PROFILE_DB_URL=${{ secrets.PROFILE_DB_URL }}
            PROFILE_DB_USERNAME=${{ secrets.PROFILE_DB_USERNAME }}
            PROFILE_DB_PASSWORD=${{ secrets.PROFILE_DB_PASSWORD }}
            TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
            LIKES_DB_URL=${{ secrets.LIKES_DB_URL }}
            LIKES_DB_USERNAME=${{ secrets.LIKES_DB_USERNAME }}
            LIKES_DB_PASSWORD=${{ secrets.LIKES_DB_PASSWORD }}
            EOF
            
            docker compose down
            ./mvnw clean package -DskipTests
            docker compose build
            docker compose up -d
