name: Deploy to remote server

on:
  push:
    branches:
      - main
      - backend

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up environment
        run: |
          docker run -d \
          -e POSTGRES_USER=postgres \
          -e POSTGRES_PASSWORD=postgres \
          -p 5432:5432 \
          -v ${{ github.workspace }}/backend/.init-db:/docker-entrypoint-initdb.d \
          postgres:17

      - name: Set up variables
        run:
          cat > .env <<EOF
          PROFILE_DB_URL=jdbc:postgresql:gymbro_db
          PROFILE_DB_USERNAME=${{ secrets.PROFILE_DB_USERNAME }}
          PROFILE_DB_PASSWORD=${{ secrets.PROFILE_DB_PASSWORD }}
          TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
          LIKES_DB_URL=${{ secrets.LIKES_DB_URL }}
          LIKES_DB_USERNAME=${{ secrets.LIKES_DB_USERNAME }}
          LIKES_DB_PASSWORD=${{ secrets.LIKES_DB_PASSWORD }}
          EOF

      - name: Compile project
        run: ./mvnw package

      - name: Run tests
        run: ./mvnw test