name: Test code on runner

on:
  push:
    branches:
      - main
      - backend

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up environment
        run: |
          docker run -d \
          -e POSTGRES_USER=postgres \
          -e POSTGRES_PASSWORD=postgres \
          -p 5432:5432 \
          -v ${{ github.workspace }}/backend/.init-db:/docker-entrypoint-initdb.d \
          postgres:17

      - name: Set up variables
        working-directory: ./backend
        run: |
          cat > .env << .env.example

      - name: Compile project
        working-directory: ./backend
        run: ./mvnw clean package -DskipTests

      - name: Run tests
        working-directory: ./backend
        run: ./mvnw test